## Esercizi sui Numpy array  5 Marzo 2024


**Esercizio 1**

Confrontare il tempo di esecuzione dei due metodi per la creazione di un numpy array di 2000000 di elementi equidistanti nell'intervallo [-4,4]:

    1) costruzione con utilizzo di np.linspace
    
    2) Assegnazione manuale dei valori nel ciclo.
    

In [2]:
import numpy as np
import time
num = 20000000

# PRIMO CASO:
start = time.perf_counter()
step = 8 / num
a = -4
x = []
for i in range(0, num):
    x.append(a+i*step)
end = time.perf_counter()
print("Tempo di esecuzione array standard: ", end - start)

# SECONDO CASO:
start = time.perf_counter()
x = np.linspace(-4,4,num)
end = time.perf_counter()
print("Tempo di esecuzione NumPy array: ", end - start)

Tempo di esecuzione array standard:  3.0798503998667
Tempo di esecuzione NumPy array:  0.21168159996159375


**Esercizio 2**

-     Creare un numpy array 1D (chiamato c) di valori equidistanti tra 7 e 41 con step 2.

-      Trasformare l'array c in un numpy array 2d (chiamato c1) con shape (2,9) usando il metodo .reshape((m,n))

-       Determinare se c1 e' una copia o una vista dell'originale.

In [3]:
c = np.arange(7,42,2)
print("Array iniziale: ")
print(c)
d = np.reshape(c,(2,9))
print("Array 2D dopo reshape: ")
print(d)
if np.shares_memory(c,d) == True:
    print("Shares memory: True")
    print("Condividono lo stesso spazio di memoria")
else:
    print("Shares memory: False")
    print("Non condividono lo stesso spazio di memoria")
    

Array iniziale: 
[ 7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41]
Array 2D dopo reshape: 
[[ 7  9 11 13 15 17 19 21 23]
 [25 27 29 31 33 35 37 39 41]]
Shares memory: True
Condividono lo stesso spazio di memoria


**Esercizio 3**

-     Costruire un numpy array 1d, denominato $C$ di valori che variano tra 15 e 41 con step 2

-     Trasformarlo in un numpy array 2d con shape(7,2) usando il metodo . resize(7,2)  che lavora in-place,  (cioè  modifica l'array esistente, non è necessario creare una copia). Verificare la shape di C e dire se C è copia o vista?

In [4]:
C = np.arange(15,41,2)
print("Array iniziale: ")
print(C)

C.resize(7,2)
print("Array 2D dopo resize: ")
print(C)

# CONTROLLO SE E' VISTA OPPURE NO:
if C.base == None:
    print("Si tratta di una copia")
else:
    print("Si tratta di una view")

Array iniziale: 
[15 17 19 21 23 25 27 29 31 33 35 37 39]
Array 2D dopo resize: 
[[15 17]
 [19 21]
 [23 25]
 [27 29]
 [31 33]
 [35 37]
 [39  0]]
Si tratta di una copia


**Esercizio 4**

-      Costruire il numpy array  s  formato da 100 valori equidistanti in  [0,4],

-      considerarne il reshape in un array 2d che ha 4 righe con un numero opportuno di colonne

In [5]:
s = np.linspace(0,4,100)
print("Array iniziale: ")
print(s)
t = np.reshape(s, (4,-1))
print("Array bidimensionale creato: ")
print(t)


Array iniziale: 
[0.         0.04040404 0.08080808 0.12121212 0.16161616 0.2020202
 0.24242424 0.28282828 0.32323232 0.36363636 0.4040404  0.44444444
 0.48484848 0.52525253 0.56565657 0.60606061 0.64646465 0.68686869
 0.72727273 0.76767677 0.80808081 0.84848485 0.88888889 0.92929293
 0.96969697 1.01010101 1.05050505 1.09090909 1.13131313 1.17171717
 1.21212121 1.25252525 1.29292929 1.33333333 1.37373737 1.41414141
 1.45454545 1.49494949 1.53535354 1.57575758 1.61616162 1.65656566
 1.6969697  1.73737374 1.77777778 1.81818182 1.85858586 1.8989899
 1.93939394 1.97979798 2.02020202 2.06060606 2.1010101  2.14141414
 2.18181818 2.22222222 2.26262626 2.3030303  2.34343434 2.38383838
 2.42424242 2.46464646 2.50505051 2.54545455 2.58585859 2.62626263
 2.66666667 2.70707071 2.74747475 2.78787879 2.82828283 2.86868687
 2.90909091 2.94949495 2.98989899 3.03030303 3.07070707 3.11111111
 3.15151515 3.19191919 3.23232323 3.27272727 3.31313131 3.35353535
 3.39393939 3.43434343 3.47474747 3.51515152 3.

**Esercizio 5**

-     Costruire il numpy array s formato da 100 valori equidistanti in  [0,4]
-     considerarne il reshape in un array 2d che ha 4 colonne con un numero opportuno di righe

In [6]:
s = np.linspace(0,4,100)
print("Array iniziale: ")
print(s)
t = np.reshape(s, (-1,4))
print("Array bidimensionale creato: ")
print(t)


Array iniziale: 
[0.         0.04040404 0.08080808 0.12121212 0.16161616 0.2020202
 0.24242424 0.28282828 0.32323232 0.36363636 0.4040404  0.44444444
 0.48484848 0.52525253 0.56565657 0.60606061 0.64646465 0.68686869
 0.72727273 0.76767677 0.80808081 0.84848485 0.88888889 0.92929293
 0.96969697 1.01010101 1.05050505 1.09090909 1.13131313 1.17171717
 1.21212121 1.25252525 1.29292929 1.33333333 1.37373737 1.41414141
 1.45454545 1.49494949 1.53535354 1.57575758 1.61616162 1.65656566
 1.6969697  1.73737374 1.77777778 1.81818182 1.85858586 1.8989899
 1.93939394 1.97979798 2.02020202 2.06060606 2.1010101  2.14141414
 2.18181818 2.22222222 2.26262626 2.3030303  2.34343434 2.38383838
 2.42424242 2.46464646 2.50505051 2.54545455 2.58585859 2.62626263
 2.66666667 2.70707071 2.74747475 2.78787879 2.82828283 2.86868687
 2.90909091 2.94949495 2.98989899 3.03030303 3.07070707 3.11111111
 3.15151515 3.19191919 3.23232323 3.27272727 3.31313131 3.35353535
 3.39393939 3.43434343 3.47474747 3.51515152 3.

**Esercizio 6**  

-     Scrivere il numpy  array 2d, A, [[10,11,12],[13,14,15],[16,17,18]] 
-     trasformarlo in un numpy array 1d usando il metodo .ravel()  
-     Si tratta di una copia o di una vista?

In [7]:
A = np.array([[10,11,12],[13,14,15],[16,17,18]])
print("Array iniziale 2D:")
print(A)
B = A.ravel()
print("Array 1D:")
print(B)
# Se nella prossima stampa viene fuori un valore diverso da None, allora è una view
print("Base:")
print(B.base)

Array iniziale 2D:
[[10 11 12]
 [13 14 15]
 [16 17 18]]
Array 1D:
[10 11 12 13 14 15 16 17 18]
Base:
[[10 11 12]
 [13 14 15]
 [16 17 18]]


**Esercizio 7**  

-     Scrivere il numpy  array 2d, A, [[10,11,12],[13,14,15],[16,17,18]] 
-     trasformarlo in un numpy array 1d usando il metodo  .flatten().
-     Si tratta di una copia o di una vista?

In [8]:
A = np.array([[10,11,12],[13,14,15],[16,17,18]])
print("Array iniziale 2D:")
print(A)
B = A.flatten()
print("Array 1D:")
print(B)
# Se nella prossima stampa viene fuori un valore diverso da None, allora è una view
print("Base:")
print(B.base)

Array iniziale 2D:
[[10 11 12]
 [13 14 15]
 [16 17 18]]
Array 1D:
[10 11 12 13 14 15 16 17 18]
Base:
None


**Esercizio 8** 

-     creare i due  numpy array 1d
        f1= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]  
        f2= [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
-     "vederli" come matrici  4x4 ed effettuarne il prodotto scalare, memorizzando in f3 la matrice che nasce dal loro prodotto.

In [9]:
f1 = np.array([ 0, 1, 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
print("Primo array (prima)")
print(f1)
f1 = np.reshape(f1, (4,4))
print("Primo array (dopo)")
print(f1)
f2 = np.array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])
print("Secondo array (prima)")
print(f2)
f2 = np.reshape(f2, (4,4))
print("Secondo array (dopo)")
print(f2)
f3 = f1 @ f2
print("Matrice finale")
print(f3)

Primo array (prima)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Primo array (dopo)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Secondo array (prima)
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
Secondo array (dopo)
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
Matrice finale
[[ 152  158  164  170]
 [ 504  526  548  570]
 [ 856  894  932  970]
 [1208 1262 1316 1370]]


**Esercizio 9**    

 Costruire:
-      Numpy Array A di shape (2,10) : array di valori random campionati da una distribuzione gaussiana con media 0 e varianza 1.
 -     Numpy array 1D B di shape (20,) formato dagli interi da 0 a 19.
 
 "Vedere" A come un array 1D di 20 elementi ed effettuare la somma di A+B



In [10]:
# RICORDA CHE UNA DISTRIBUZIONE GAUSSIANA SI CHIAMA ANCHE DISTRIBUZIONE NORMALE STANDARD:
A = np.array(np.random.randn(2,10))
print("Array di valori random campionati da una distribuzione normale standard:")
print(A)
B = np.array(np.arange(0,20,1))
print("Array di tutti i valori compresi fra 0 e 19")
print(B)

# Procedo a fare il reshape di A, per farlo diventare un array 1D di 20 elementi:
A.resize(20)
print("Array 2D trasformato in 1D:")
print(A)

# Procedo a fare la somma dei due array 1D:
C = A + B
print("Somma fra i due array precedenti:")
print(C)

Array di valori random campionati da una distribuzione normale standard:
[[ 0.93220545 -1.90681065  0.72340877 -0.87171297  0.71932019  1.03017721
  -0.67043916 -0.42596806 -1.28326736 -0.40257156]
 [ 1.12056944 -0.40621381  1.09439859  0.28908569  0.13524198  0.05381033
  -0.38420427 -0.22436136 -0.30860887 -0.46857431]]
Array di tutti i valori compresi fra 0 e 19
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Array 2D trasformato in 1D:
[ 0.93220545 -1.90681065  0.72340877 -0.87171297  0.71932019  1.03017721
 -0.67043916 -0.42596806 -1.28326736 -0.40257156  1.12056944 -0.40621381
  1.09439859  0.28908569  0.13524198  0.05381033 -0.38420427 -0.22436136
 -0.30860887 -0.46857431]
Somma fra i due array precedenti:
[ 0.93220545 -0.90681065  2.72340877  2.12828703  4.71932019  6.03017721
  5.32956084  6.57403194  6.71673264  8.59742844 11.12056944 10.59378619
 13.09439859 13.28908569 14.13524198 15.05381033 15.61579573 16.77563864
 17.69139113 18.53142569]


**Esercizio 10** 
-     Creare un array 2D di shape (5,5), denominato B2, con valori tutti uguali a 15.
-     Creare una copia B3 di B2. Modificare l'elemento B3[0,0] assegnandogli il valore 150. 
-     Stampare il numpy array B2 ed il numpy array B3 e verificare che B2, dopo la modifica di B3, è rimasto inalterato

In [11]:
B2 = np.array(np.full((5,5),15))
print("Array con tutti valori uguali a 15")
print(B2)
B3 = B2.copy()
B3[0][0] = 150
print("Array originale dopo la modifica della copia:")
print(B2)
print("Array copia di quello precedente:")
print(B3)

Array con tutti valori uguali a 15
[[15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]]
Array originale dopo la modifica della copia:
[[15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]]
Array copia di quello precedente:
[[150  15  15  15  15]
 [ 15  15  15  15  15]
 [ 15  15  15  15  15]
 [ 15  15  15  15  15]
 [ 15  15  15  15  15]]


**Esercizio 11**   

-     Costruire  un numpy array 1D, di shape (10,) denominato  f , costituito da 10 valori equidistanti nell'intervallo [0,1]
-     aumentarne la dimensionalità, in maniera tale che abbia shape (10,1)

In [12]:
f = np.array(np.linspace(0,1,10))
print("Array di 10 valori equidistanti nell'intervallo 0-1:")
print(f)

# Modifico la shape:
f = np.reshape(f, (10,1))
print("Array dopo la modifica della dimensionalità:")
print(f)

Array di 10 valori equidistanti nell'intervallo 0-1:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Array dopo la modifica della dimensionalità:
[[0.        ]
 [0.11111111]
 [0.22222222]
 [0.33333333]
 [0.44444444]
 [0.55555556]
 [0.66666667]
 [0.77777778]
 [0.88888889]
 [1.        ]]


**Esercizio 12**
-     Costruire i seguenti numpy array
      a= np.array([14,13,12,11])
      b=np.array([[4,3,2,1],[9,10,11,12]])

  Costruire il numpy array che si ottiene concatenando a e b per righe

In [13]:
a = np.array([14,13,12,11])
a.resize(2,4)
b = np.array([[4,3,2,1],[9,10,11,12]])
print("Primo array originale:")
print(a)
print("Secondo array originale:")
print(b)

# Per concatenare gli array per righe, devo usare il comando .concatenate():
print("Array finale generato come concatenamento delle righe degli array originali:")
print(np.concatenate((a,b), axis = 0))

Primo array originale:
[[14 13 12 11]
 [ 0  0  0  0]]
Secondo array originale:
[[ 4  3  2  1]
 [ 9 10 11 12]]
Array finale generato come concatenamento delle righe degli array originali:
[[14 13 12 11]
 [ 0  0  0  0]
 [ 4  3  2  1]
 [ 9 10 11 12]]


**Esercizio 13**
-     Costruire i seguenti numpy array
      a= np.array([14,13,12,11])
      b=np.array([[4,3,2,1],[9,10,11,12],[4,3,2,1],[9,10,11,12]])
- Costruire il numpy array che si ottiene concatenando a e b per colonne

In [14]:
a = np.array([14,13,12,11])
a.resize(4,1)
b = np.array([[4,3,2,1],[9,10,11,12],[4,3,2,1],[9,10,11,12]])
print("Primo array originale:")
print(a)
print("Secondo array originale:")
print(b)

# Per concatenare gli array per righe, devo usare il comando .concatenate():
print("Array finale generato come concatenamento delle righe degli array originali:")
print(np.concatenate((a,b), axis = 1))

Primo array originale:
[[14]
 [13]
 [12]
 [11]]
Secondo array originale:
[[ 4  3  2  1]
 [ 9 10 11 12]
 [ 4  3  2  1]
 [ 9 10 11 12]]
Array finale generato come concatenamento delle righe degli array originali:
[[14  4  3  2  1]
 [13  9 10 11 12]
 [12  4  3  2  1]
 [11  9 10 11 12]]


**Esercizio 14**

Costruire, facendo uso di una sola riga di codice, la matrice A di ordine 10, che ha gli unici elementi diversi da zero, sulla diagonale princiaple, sulla codiagonale inferiore e sulla codiagonale superiore:
- elementi diagonali $A_{i,i}=10 \quad$, i=1,20
- elementi nella codiagonale inferiore $A_{i-1,i}=-12, \quad$ i=2,..,20, 
- elementi nella codiagonale superiore $A_{i,i+1}=-2 \quad$ i=1,..,19

In [15]:
A = np.diag(np.tile([10], 10)) + np.diag(np.tile([-12], 9), k = -1) + np.diag(np.tile([-2], 9), k = 1)
print(A)

[[ 10  -2   0   0   0   0   0   0   0   0]
 [-12  10  -2   0   0   0   0   0   0   0]
 [  0 -12  10  -2   0   0   0   0   0   0]
 [  0   0 -12  10  -2   0   0   0   0   0]
 [  0   0   0 -12  10  -2   0   0   0   0]
 [  0   0   0   0 -12  10  -2   0   0   0]
 [  0   0   0   0   0 -12  10  -2   0   0]
 [  0   0   0   0   0   0 -12  10  -2   0]
 [  0   0   0   0   0   0   0 -12  10  -2]
 [  0   0   0   0   0   0   0   0 -12  10]]


**Esercizio 15**

Costruire la matrice identità, denominata *I*,  della stessa dimensione di *A*

In [25]:
dim1, dim2 = A.shape
print("La matrice A è una matrice:", dim1, "*", dim2)
I = np.eye(dim1)
print("Matrice identità della stessa dimensione di A:")
print(I)

La matrice A è una matrice: 10 * 10
Matrice identità della stessa dimensione di A:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


**Esercizio 16**

Facendo uso dell'operatore slicing *:* ,costruire la matrice AA selezionando dalla matrice A le righe che vanno dalla 2 alla 9 con step 2 e le colonne che vanno dalla 3 alla 6 con step 2.
La matrice AA è una vista o una copia?


In [31]:
AA = A[2:9:2]
print("Stampa della matrice ottenuta con l'operatore di slicing:")
print(AA)
# Essendo che la base non è None, allora si tratta di una vista della matrice originale
print("Stampa della base della matrice ottenuta:")
print(AA.base)

Stampa della matrice ottenuta con l'operatore di slicing:
[[  0 -12  10  -2   0   0   0   0   0   0]
 [  0   0   0 -12  10  -2   0   0   0   0]
 [  0   0   0   0   0 -12  10  -2   0   0]
 [  0   0   0   0   0   0   0 -12  10  -2]]
Stampa della base della matrice ottenuta:
[[ 10  -2   0   0   0   0   0   0   0   0]
 [-12  10  -2   0   0   0   0   0   0   0]
 [  0 -12  10  -2   0   0   0   0   0   0]
 [  0   0 -12  10  -2   0   0   0   0   0]
 [  0   0   0 -12  10  -2   0   0   0   0]
 [  0   0   0   0 -12  10  -2   0   0   0]
 [  0   0   0   0   0 -12  10  -2   0   0]
 [  0   0   0   0   0   0 -12  10  -2   0]
 [  0   0   0   0   0   0   0 -12  10  -2]
 [  0   0   0   0   0   0   0   0 -12  10]]


**Esercizio 17**

Facendo uso dell'operatore slicing *:*, costruire la matrice A1 selezionando dalla matrice A le colonne che vanno dalla 1 alla 5 con step 2.  Trasforma la matrice A1 in una copia.

In [38]:
import copy
# Potevo anche usare il metodo .deepcopy():
A1 = A[1:5:2].copy()
print("Stampa della matrice ottenuta con l'operatore di slicing:")
print(AA)
# Essendo che la base non è None, allora si tratta di una vista della matrice originale
print("Stampa della base della matrice ottenuta:")
print(A1.base)

Stampa della matrice ottenuta con l'operatore di slicing:
[[  0 -12  10  -2   0   0   0   0   0   0]
 [  0   0   0 -12  10  -2   0   0   0   0]
 [  0   0   0   0   0 -12  10  -2   0   0]
 [  0   0   0   0   0   0   0 -12  10  -2]]
Stampa della base della matrice ottenuta:
None


**Esercizio 18**

Costruisci due numpy array A e B di shape (5,5) 
   - A formata da numeri interi casuali  nell'intervallo [1,20]
   - B formata da numeri interi casuali  nell'intervallo [1,6]
 
  Costruisci con una sola riga di codice le seguenti matrici
  
  C=A+B   dove  $\quad c_{ij}=a_{ij}+b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  D=A-B   dove  $\quad d_{ij}=a_{ij}-b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  E=A*B   dove  $\quad e_{ij}=a_{ij}*b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  F=A\B   dove  $\quad f_{ij}=a_{ij}\b_{ij} \quad i=0,..,n, \quad j=0,...,n$

In [54]:
# Ricorda che randint() vuole come parametri: low, high, size(che può essere una shape)
A = np.random.randint(1, 20, (5,5))
print("Prima matrice:")
print(A)
B = np.random.randint(1, 6, (5,5))
print("Seconda matrice:")
print(B)

# Somma delle matrici
C = A + B
print("Somma matriciale:")
print(C)

# Differenza delle matrici
D = A - B
print("Differenza matriciale:")
print(D)

# Prodotto delle matrici
# si poteva anche fare semplicemente A * B (funzionava ugualmente)
E = np.multiply(A, B)
print("Prodotto matriciale:")
print(E)

# Quoziente delle matrici
# si poteva anche fare semplicemente A / B (funzionava ugualmente)
F = np.divide(A, B)
print("Quoziente matriciale:")
print(F)

Prima matrice:
[[14  5  9 13  5]
 [ 3  6  5  1 19]
 [17 18 18 17  2]
 [ 8 12  1 17 14]
 [16 18  9  3 14]]
Seconda matrice:
[[4 1 2 1 1]
 [3 4 1 4 5]
 [4 5 5 2 5]
 [1 5 1 2 3]
 [2 1 4 1 2]]
Somma matriciale:
[[18  6 11 14  6]
 [ 6 10  6  5 24]
 [21 23 23 19  7]
 [ 9 17  2 19 17]
 [18 19 13  4 16]]
Differenza matriciale:
[[10  4  7 12  4]
 [ 0  2  4 -3 14]
 [13 13 13 15 -3]
 [ 7  7  0 15 11]
 [14 17  5  2 12]]
Prodotto matriciale:
[[56  5 18 13  5]
 [ 9 24  5  4 95]
 [68 90 90 34 10]
 [ 8 60  1 34 42]
 [32 18 36  3 28]]
Quoziente matriciale:
[[ 3.5         5.          4.5        13.          5.        ]
 [ 1.          1.5         5.          0.25        3.8       ]
 [ 4.25        3.6         3.6         8.5         0.4       ]
 [ 8.          2.4         1.          8.5         4.66666667]
 [ 8.         18.          2.25        3.          7.        ]]


**Esercizio 19**

Costruisci la matrice ottenuta facendo il prodotto scalare tra le  matrici A e B (righe per colonne)

In [56]:
# Si poteva anche utilizzare il metodo .dot()
Prod_Scalare = A @ B
print("Matrice ottenuta per prodotto scalare fra le due matrici A e B:")
print(Prod_Scalare)

Matrice ottenuta per prodotto scalare fra le due matrici A e B:
[[130 149 111  83 133]
 [ 89  76 114  58  99]
 [215 266 167 161 252]
 [117 160 106 106 152]
 [185 162 154 126 188]]


**Esercizio 20**

Costruisci l'array ottenuto sommando gli elementi delle righe della matrice B usando l'appropriata funzione di Numpy.

In [57]:
print("Matrice originaria B:")
print(B)
Somma_righe = np.sum(B, axis = 0)
print("Array ottenuto per somma delle righe di B:")
print(Somma_righe)

Matrice originaria B:
[[4 1 2 1 1]
 [3 4 1 4 5]
 [4 5 5 2 5]
 [1 5 1 2 3]
 [2 1 4 1 2]]
Array ottenuto per somma delle righe di B:
[14 16 13 10 16]


**Esercizio 21** 

Costruisci l'array ottenuto sommando gli elementi delle colonne della matrice B usando l'appropriata funzione di Numpy.

In [59]:
print("Matrice originaria B:")
print(B)
Somma_righe = np.sum(B, axis = 1)
print("Array ottenuto per somma delle colonne di B:")
print(Somma_righe)

Matrice originaria B:
[[4 1 2 1 1]
 [3 4 1 4 5]
 [4 5 5 2 5]
 [1 5 1 2 3]
 [2 1 4 1 2]]
Array ottenuto per somma delle colonne di B:
[ 9 17 21 12 10]


**Esercizio 22** 

Somma tutti gli elementi di B usando l'appropriata funzione di Numpy.

In [61]:
print("Matrice originaria B:")
print(B)
Somma_righe = np.sum(B)
print("Somma di tutti i valori presenti in B:")
print(Somma_righe)

Matrice originaria B:
[[4 1 2 1 1]
 [3 4 1 4 5]
 [4 5 5 2 5]
 [1 5 1 2 3]
 [2 1 4 1 2]]
Somma di tutti i valori presenti in B:
69


**Esercizio 23**

Calcolare il minimo degli elementi di B, tra le righe, tra le colonne, il minimo di tutta la matrice B

**Esercizio 24**

Calcola e memorizza in un vettore la somma degli elementi di ogni colonna di $ |B |$. Calcola successivamente il massimo di questo vettore.
$maxsc= \max_{j=1,n} \sum_{i} |b_{ij}|$

**Esercizio 25**
Calcola, memorizzando in un vettore, la somma degli elementi di ogni riga  di $ |B |$. Calcola successivamente il massimo di questo vettore.
$maxsr= \max_{i=1,n} \sum_{j} |b_{ij}|$

**Esercizio 26**

Effettua nella matrice B lo scambio tra la  riga 2 e  la riga 3

**Esercizio 27**

Calcola il valore massimo della colonna 0-esima della matrice B e l'indice di riga a cui appartiene

**Esercizio 28**   


Scrivi una funzione border(m,n,visualizza=False) che:
-      crea un array 2D di shape(m,n) che abbia tutti valori nulli
-     imposta ad 1  i valori degli elementi sul bordo dell'array (prima ed ultima riga, prima e l'ultima colonna)
-      Preveda un argomento di default che se impostato a True visualizza la matrice

**Esercizio 29**

Scrivi una funzione `visualizza(f,a,b)`che prende in input una lambda function f, gli estremi dell'intervallo [a,b] su cui è definita e la visualizzi in una finestra grafica

Chaima la funzione passandogli la funzione f(x)=sin(2*$\pi$*x), [a,b]=[0,2*$\pi$]

**Esercizio 30**

Scrivi una funzione `visualizza2(f,a,b,f2,a2,b2)`che prende in input una lambda function f e gli estremi dell'intervallo [a,b]  su cui è definita, una lambda function f2 e gli estremi dell'intervallo su cui è definita [a2,b2] e le visualizzi sulla stessa finestra grafica.

Chaima la funzione passandogli  una funzione f(x) quadratica ed una funzione f2(x) exponenziale ed [a,b]=[0,2]